# Generated by Django 5.2 on 2025-04-10 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('disabled', 'Disabled'), ('in_review', 'In Review'), ('rejected', 'Rejected'), ('published', 'Published')], default='process', max_length=100),
        ),
    ]
