# Generated by Django 5.2 on 2025-04-21 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_product_desc_alter_vendor_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='get_percentage',
            field=models.DecimalField(decimal_places=0, default=100, max_digits=10),
        ),
    ]
