# Generated by Django 5.2 on 2025-08-06 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_product_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_review',
            name='Product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review', to='core.product'),
        ),
    ]
