# Generated by Django 5.2 on 2025-08-06 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_product_review_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartorders',
            old_name='order',
            new_name='user',
        ),
    ]
