# Generated by Django 5.2 on 2025-08-07 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_order_cartorders_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartorders',
            old_name='user',
            new_name='order',
        ),
    ]
