# Generated by Django 5.2 on 2025-08-07 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_user_cartorders_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartorders',
            old_name='order',
            new_name='user',
        ),
    ]
