# Generated by Django 5.2 on 2025-08-17 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_cartitemorders_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorders',
            name='product_status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], default='process', max_length=100),
        ),
    ]
