# Generated by Django 5.2 on 2025-08-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_cartorders_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorders',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
