# Generated by Django 5.2 on 2025-08-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_cartorders_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitemorders',
            name='image',
            field=models.ImageField(default='product.jpg', upload_to='order_items'),
        ),
    ]
