# Generated by Django 5.2 on 2025-08-23 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_address_delete_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='alternate_mobile',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='address',
            name='mobile',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
